using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

public partial class A_SVMerchant_Change_password : System.Web.UI.Page
{

    SqlConnection sconn = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
    string abc;
    protected void Page_Load(object sender, EventArgs e)
    {
        try
        {
            if (Session["Expire"] != "0")
            {
                if (Session["user"] != "" || Session["user"] != null || Session["Expire"] != "0")
                {
                    string abcd = Session["user"].ToString();
                    string abc = Session["Email_Id"].ToString();

                }
                else
                {
                    Response.Redirect("../Login.aspx");
                }
            }
            else
            {
                ScriptManager.RegisterStartupScript(this, typeof(string), "alert", "alert('Your Subscription Pack Is Expired..Please Renew Your pack')", true);
            }
        }
        catch
        {
            Response.Redirect("../Login.aspx");
        }
    }
    protected void Button2_Click(object sender, EventArgs e)
    {

        abc = Session["Email_Id"].ToString();
        if (sconn.State == ConnectionState.Open)
        {
            sconn.Close();
        }
        sconn.Open();
        SqlCommand cmd3 = new SqlCommand("SELECT * FROM  Admin_Login Where Email_Id=@Email_Id AND Password=@Password", sconn);
        cmd3.Parameters.AddWithValue("Email_Id", abc);
        cmd3.Parameters.AddWithValue("Password", txtoldpass.Text);
        SqlDataAdapter dr3 = new SqlDataAdapter(cmd3);
        DataTable dt3 = new DataTable();
        dr3.Fill(dt3);
        if (dt3.Rows.Count == 1)
        {
            if (sconn.State == ConnectionState.Open)
            {
                sconn.Close();
            }
            sconn.Open();
            SqlCommand cmd = new SqlCommand("update Admin_Login Set Password=@Password Where Email_Id='" + abc + "'", sconn);
            cmd.Parameters.AddWithValue("Password", txtnewpass.Text);
            cmd.ExecuteNonQuery();
            txtnewpass.Text = "";
            txtoldpass.Text = "";
            txtconform_password.Text = "";

            ScriptManager.RegisterStartupScript(this, typeof(string), "Alert", "alert('Password Changed Successfully ');", true);

        }
        else
        {
            ScriptManager.RegisterStartupScript(this, typeof(string), "Alert", "alert('Current Password Is Incorrect');", true);

        }
    }
    private void Page_Error(object sender, EventArgs e)
    {
        // Get last error from the server
        Exception exc = Server.GetLastError();

        // Handle exceptions generated by Button 1
        if (exc is InvalidOperationException)
        {
            // Pass the error on to the Generic Error page
            Server.Transfer("GenericErrorPage.aspx", true);
        }

        // Handle exceptions generated by Button 2
        else if (exc is ArgumentOutOfRangeException)
        {
            // Give the user some information, but
            // stay on the default page
            Response.Write("<h2>Default Page Error</h2>\n");
            Response.Write("<p>Provide as much information here as is " +
              "appropriate to show to the client.</p>\n");
            Response.Write("Return to the <a href='Default.aspx'>" +
                "Default Page</a>\n");

            // Log the exception and notify system operators
            ParkingMy.Logic.ExceptionUtility.LogException(exc, "DefaultPage");
            ParkingMy.Logic.ExceptionUtility.NotifySystemOps(exc);

            // Clear the error from the server
            Server.ClearError();
        }
        else
        {
            // Pass the error on to the default global handler
        }
    }
}