using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

public partial class Admin_Add_Space : System.Web.UI.Page
{
    SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        if (con.State == ConnectionState.Open)
        {
            con.Close();
        }
        con.Open();
        if (txtspace.Text == "")
        {
            ScriptManager.RegisterStartupScript(this, typeof(string), "Alert", "alert('Fill Up All Details');", true);
            txtspace.Text = "";
        }
        else
        {
            SqlCommand cmd2 = new SqlCommand("select * from Admin_Space where Space='" + txtspace.Text + "'", con);
            SqlDataAdapter da = new SqlDataAdapter(cmd2);
            DataSet ds = new DataSet();
            da.Fill(ds, "Admin_Space");
            if (ds.Tables["Admin_Space"].Rows.Count > 0)
            {

                ScriptManager.RegisterStartupScript(this, typeof(string), "Alert", "alert(' Already Exit ');", true);

            }
            else
            {
                string s = txtspace.Text;
                s = System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ToTitleCase(s.ToLower());
                txtspace.Text = s.ToString();

                SqlCommand cmd = new SqlCommand("insert into Admin_Space(Space)values(@Space)", con);
                cmd.Parameters.AddWithValue("@Space", txtspace.Text);
                cmd.ExecuteNonQuery();
                txtspace.Text = "";

                ScriptManager.RegisterStartupScript(this, typeof(string), "Alert", "alert(' Date Insert Successfully ');", true);
                GridView1.DataBind();
                con.Close();
            }
        }
    }
    private void Page_Error(object sender, EventArgs e)
    {
        // Get last error from the server
        Exception exc = Server.GetLastError();

        // Handle exceptions generated by Button 1
        if (exc is InvalidOperationException)
        {
            // Pass the error on to the Generic Error page
            Server.Transfer("GenericErrorPage.aspx", true);
        }

        // Handle exceptions generated by Button 2
        else if (exc is ArgumentOutOfRangeException)
        {
            // Give the user some information, but
            // stay on the default page
            Response.Write("<h2>Default Page Error</h2>\n");
            Response.Write("<p>Provide as much information here as is " +
              "appropriate to show to the client.</p>\n");
            Response.Write("Return to the <a href='Default.aspx'>" +
                "Default Page</a>\n");

            // Log the exception and notify system operators
            ParkingMy.Logic.ExceptionUtility.LogException(exc, "DefaultPage");
            ParkingMy.Logic.ExceptionUtility.NotifySystemOps(exc);

            // Clear the error from the server
            Server.ClearError();
        }
        else
        {
            // Pass the error on to the default global handler
        }
    }
}