using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class User_ParkingMyLockup : System.Web.UI.Page
{
    string ss, xxx, sss;
    int idd;
    string abbb;
    string area, city, state, country;
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void Button1_Click(object sender, EventArgs e)
    {

       
    }
    protected void btnSearch_Click(object sender, EventArgs e)
    {
       
    }
    protected void jack(object sender, EventArgs e)
    {
        string input = txtSearch.Text;

        string[] data = txtSearch.Text.Split(',');
        if (data.Length == 4)
        {
            area = data[0];
            city = data[1];
            state = data[2];
            country = data[3];
            Session["areaa"] = area.Trim();
            Session["cityy"] = city.Trim();
            Session["statee"] = state.Trim();
            Session["countyrr"] = country.Trim();
            Session["lat"] = txtLat.Text.Trim();
            Session["long"] = txtLng.Text.Trim();
            Panel1.Visible = true;
            Button1.Visible = false;
        }
        else if (data.Length == 5)
        {
            area = data[1];
            city = data[2];
            state = data[3];
            country = data[4];
            Session["areaa"] = area.Trim();
            Session["cityy"] = city.Trim();
            Session["statee"] = state.Trim();
            Session["countyrr"] = country.Trim();
            Session["lat"] = txtLat.Text.Trim();
            Session["long"] = txtLng.Text.Trim();
            Panel1.Visible = true;
            Button1.Visible = false;
        }
        else if (data.Length == 6)
        {
            area = data[2];
            city = data[3];
            state = data[4];
            country = data[5];
            Session["areaa"] = area.Trim();
            Session["cityy"] = city.Trim();
            Session["statee"] = state.Trim();
            Session["countyrr"] = country.Trim();
            Session["lat"] = txtLat.Text.Trim();
            Session["long"] = txtLng.Text.Trim();
            Panel1.Visible = true;
            Button1.Visible = false;
        }
        else
        {
            Panel1.Visible = false;
            Button1.Visible = true;
        }
    }
    private void Page_Error(object sender, EventArgs e)
    {
        // Get last error from the server
        Exception exc = Server.GetLastError();

        // Handle exceptions generated by Button 1
        if (exc is InvalidOperationException)
        {
            // Pass the error on to the Generic Error page
            Server.Transfer("GenericErrorPage.aspx", true);
        }

        // Handle exceptions generated by Button 2
        else if (exc is ArgumentOutOfRangeException)
        {
            // Give the user some information, but
            // stay on the default page
            Response.Write("<h2>Default Page Error</h2>\n");
            Response.Write("<p>Provide as much information here as is " +
              "appropriate to show to the client.</p>\n");
            Response.Write("Return to the <a href='Default.aspx'>" +
                "Default Page</a>\n");

            // Log the exception and notify system operators
            ParkingMy.Logic.ExceptionUtility.LogException(exc, "DefaultPage");
            ParkingMy.Logic.ExceptionUtility.NotifySystemOps(exc);

            // Clear the error from the server
            Server.ClearError();
        }
        else
        {
            // Pass the error on to the default global handler
        }
    }
   
}